FROM python:3.10.13
WORKDIR /app
COPY backend/requirements.txt /app/
RUN apt-get update && \
    apt-get install -y libpq-dev && \
    apt-get install -y build-essential && \
    apt-get install -y liblapack-dev gcc g++ gfortran musl-dev libffi-dev python3-dev libopenblas-dev && \
    pip install -r /app/requirements.txt
COPY backend /app